### ISSUE TITLE
生成ast树的时候，没有修改currentParent指向

### ISSUE THREAD

**Issue by share-man-man** [zhufengzhufeng/vue-source#2]
// src/compiler/parser.js解析文件的结束标签方法
function end(tagName) {
        // console.log(tagName)
        // 删除栈中的开始标签
        let element = stack.pop();
        let parent = stack[stack.length-1];
        if(parent){
            element.parent = parent;
            parent.children.push(element);
            // 标签结束后，修改当前父节点
            currentParent = parent
        }

**Comment by zhufengzhufeng** [comment]
感谢 已经修复   currentParent = stack[stack.length-1];
